### PR TITLE
Update some patterns

### PR DESCRIPTION
**Pull request by Dh0mp5eur**

### CODE REVIEW

**Comment by whyscream** [comment]
Where did you find the unknown IP address snippets for smtpd and anvil? Seems very weird behaviour from postfix to me. Could you post complete postfix logs for those transactions?

**Comment by whyscream** [comment]
I merged the `SSL_accept error` and the `pipe` pattern updates, hoping to hear more about the 3rd line.

**Comment by Dh0mp5eur** [comment]
The person has changed subnetworks.
Probably it is the time that the ARP table is empty.

postfix/smtpd[6248]: connect from unknown[10.133.20.22]
postfix/smtpd[6248]: connect from unknown[unknown]
postfix/smtpd[6248]: lost connection after CONNECT from unknown[unknown]
postfix/smtpd[6248]: disconnect from unknown[unknown]
postfix/smtpd[6248]: lost connection after CONNECT from unknown[10.130.10.12]

**Comment by whyscream** [comment]
Parsing this does not help anything, since (imho) you should be able to trust that data in  `postfix_client_ip` is actually an ip address. The fact that the common pattern fails will simply help you detect this networking anomaly, but a fix for it shouldn't be part of the default parsing strategy.

**Pull request closed without merging**
